# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CI"]
    branches: [ main ]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.sha }}
          check-name: build
          running-workflow-name: 'CI'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: wait
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  set_status:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      statuses: write 
    steps:
      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "CI2",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail
